// Auto-generated by npm run generate:tests.
// Do not edit directly; update api/index.json or nodes/Dokaai/operations.ts.

const assert = require('node:assert/strict');
const test = require('node:test');

const { Dokaai } = require('../../index');
const { dokaaiOpenApiDocument } = require('../../nodes/Dokaai/shared/document');
const { findOperationById, buildRequestOptions } = require('../../nodes/Dokaai/openapi/runtime');
const { readOperationValues } = require('../../nodes/Dokaai/shared/values');

const operationsByResource = {
  "customer": [
    "addCustomersToPool",
    "updateCustomerInPool",
    "removeCustomerFromPool",
    "getPoolCustomers",
    "getPoolCustomerById"
  ],
  "customAttribute": [
    "addCustomerCustomAttribute"
  ],
  "notificationHandler": [
    "triggerNotificationHandler",
    "getNotificationHandler",
    "getAllNotificationHandlersInProject"
  ],
  "targetAudienceList": [
    "associateCustomerToTargetAudienceList",
    "deleteCustomerFromTargetAudienceList"
  ]
};
const operationFixtures = [
  {
    "operationId": "addCustomersToPool",
    "resource": "customer",
    "method": "POST",
    "parameters": [
      "customerPoolId",
      "projectId"
    ],
    "bodyFieldNames": [
      "uniqueCustomerId",
      "emailId",
      "phoneNumber",
      "iosDeviceTokens",
      "androidDeviceTokens",
      "name",
      "pinCode",
      "countryIsoCode",
      "timeZone"
    ],
    "hasCustomerAttributeMapper": true,
    "inputData": {
      "customerPoolId": "customerPoolId value",
      "projectId": "projectId value",
      "uniqueCustomerId": "uniqueCustomerId-value",
      "emailId": "emailId-value",
      "phoneNumber": "phoneNumber-value",
      "iosDeviceTokens": {
        "iosDeviceTokens": [
          {
            "value": "iosDeviceTokens-1"
          },
          {
            "value": "iosDeviceTokens-2"
          }
        ]
      },
      "androidDeviceTokens": {
        "androidDeviceTokens": [
          {
            "value": "androidDeviceTokens-1"
          },
          {
            "value": "androidDeviceTokens-2"
          }
        ]
      },
      "name": "name-value",
      "pinCode": "pinCode-value",
      "countryIsoCode": "countryIsoCode-value",
      "timeZone": "timeZone-value",
      "customerAttributes": {
        "mappingMode": "defineBelow",
        "value": {
          "test_custom_attribute": "custom-value"
        },
        "matchingColumns": [],
        "schema": [],
        "attemptToConvertTypes": false,
        "convertFieldsToString": false
      }
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/customers",
    "expectedQs": {},
    "expectedBody": {
      "customerData": {
        "uniqueCustomerId": "uniqueCustomerId-value",
        "emailId": "emailId-value",
        "phoneNumber": "phoneNumber-value",
        "iosDeviceTokens": [
          "iosDeviceTokens-1",
          "iosDeviceTokens-2"
        ],
        "androidDeviceTokens": [
          "androidDeviceTokens-1",
          "androidDeviceTokens-2"
        ],
        "name": "name-value",
        "pinCode": "pinCode-value",
        "countryIsoCode": "countryIsoCode-value",
        "timeZone": "timeZone-value",
        "test_custom_attribute": "custom-value"
      }
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  },
  {
    "operationId": "updateCustomerInPool",
    "resource": "customer",
    "method": "PUT",
    "parameters": [
      "customerPoolId",
      "customerId",
      "projectId"
    ],
    "bodyFieldNames": [
      "name",
      "countryIsoCode",
      "iosDeviceTokens",
      "androidDeviceTokens",
      "emailId",
      "phoneNumber",
      "pinCode",
      "timeZone"
    ],
    "hasCustomerAttributeMapper": true,
    "inputData": {
      "customerPoolId": "customerPoolId value",
      "customerId": "customerId value",
      "projectId": "projectId value",
      "name": "name-value",
      "countryIsoCode": "countryIsoCode-value",
      "iosDeviceTokens": {
        "iosDeviceTokens": [
          {
            "value": "iosDeviceTokens-1"
          },
          {
            "value": "iosDeviceTokens-2"
          }
        ]
      },
      "androidDeviceTokens": {
        "androidDeviceTokens": [
          {
            "value": "androidDeviceTokens-1"
          },
          {
            "value": "androidDeviceTokens-2"
          }
        ]
      },
      "emailId": "emailId-value",
      "phoneNumber": "phoneNumber-value",
      "pinCode": "pinCode-value",
      "timeZone": "timeZone-value",
      "customerAttributes": {
        "mappingMode": "defineBelow",
        "value": {
          "test_custom_attribute": "custom-value"
        },
        "matchingColumns": [],
        "schema": [],
        "attemptToConvertTypes": false,
        "convertFieldsToString": false
      }
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/customers/customerId%20value",
    "expectedQs": {},
    "expectedBody": {
      "name": "name-value",
      "countryIsoCode": "countryIsoCode-value",
      "iosDeviceTokens": [
        "iosDeviceTokens-1",
        "iosDeviceTokens-2"
      ],
      "androidDeviceTokens": [
        "androidDeviceTokens-1",
        "androidDeviceTokens-2"
      ],
      "emailId": "emailId-value",
      "phoneNumber": "phoneNumber-value",
      "pinCode": "pinCode-value",
      "timeZone": "timeZone-value",
      "test_custom_attribute": "custom-value"
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  },
  {
    "operationId": "removeCustomerFromPool",
    "resource": "customer",
    "method": "PATCH",
    "parameters": [
      "customerPoolId",
      "projectId",
      "customerId"
    ],
    "bodyFieldNames": [],
    "hasCustomerAttributeMapper": false,
    "inputData": {
      "customerPoolId": "customerPoolId value",
      "projectId": "projectId value",
      "customerId": "customerId value"
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/customer/customerId%20value/status",
    "expectedQs": {},
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  },
  {
    "operationId": "getPoolCustomers",
    "resource": "customer",
    "method": "GET",
    "parameters": [
      "projectId",
      "customerPoolId",
      "search",
      "searchField",
      "filterOutTALId",
      "page",
      "size"
    ],
    "bodyFieldNames": [],
    "hasCustomerAttributeMapper": false,
    "inputData": {
      "projectId": "projectId value",
      "customerPoolId": "customerPoolId value",
      "search": "search-value",
      "searchField": "uniqueCustomerId",
      "filterOutTALId": "filterOutTALId-value",
      "page": "page-value",
      "size": "size-value"
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/customers",
    "expectedQs": {
      "search": "search-value",
      "searchField": "uniqueCustomerId",
      "filterOutTALId": "filterOutTALId-value",
      "page": "page-value",
      "size": "size-value"
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  },
  {
    "operationId": "getPoolCustomerById",
    "resource": "customer",
    "method": "GET",
    "parameters": [
      "projectId",
      "customerId",
      "customerPoolId",
      "attributeTypes"
    ],
    "bodyFieldNames": [],
    "hasCustomerAttributeMapper": false,
    "inputData": {
      "projectId": "projectId value",
      "customerId": "customerId value",
      "customerPoolId": "customerPoolId value",
      "attributeTypes": "all"
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/customers/customerId%20value",
    "expectedQs": {
      "attributeTypes": "all"
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  },
  {
    "operationId": "addCustomerCustomAttribute",
    "resource": "customAttribute",
    "method": "POST",
    "parameters": [
      "customerPoolId",
      "projectId"
    ],
    "bodyFieldNames": [
      "customAttributes"
    ],
    "hasCustomerAttributeMapper": false,
    "inputData": {
      "customerPoolId": "customerPoolId value",
      "projectId": "projectId value",
      "customAttributes": {
        "customAttributes": [
          {
            "fieldName": "fieldName-value",
            "fieldDisplayName": "fieldDisplayName-value",
            "fieldDescription": "fieldDescription-value",
            "fieldType": "string"
          }
        ]
      }
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/customer/projects/projectId%20value/customer-pools/customerPoolId%20value/custom-attributes",
    "expectedQs": {},
    "expectedBody": {
      "customAttributes": [
        {
          "fieldName": "fieldName-value",
          "fieldDisplayName": "fieldDisplayName-value",
          "fieldDescription": "fieldDescription-value",
          "fieldType": "string"
        }
      ]
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  },
  {
    "operationId": "triggerNotificationHandler",
    "resource": "notificationHandler",
    "method": "POST",
    "parameters": [
      "projectId",
      "notificationHandlerId"
    ],
    "bodyFieldNames": [
      "mode",
      "idempotencyKey"
    ],
    "hasCustomerAttributeMapper": false,
    "inputData": {
      "projectId": "projectId value",
      "notificationHandlerId": "notificationHandlerId value",
      "mode": "live",
      "idempotencyKey": "idempotencyKey-value"
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/nudge/projects/projectId%20value/notification-handlers/notificationHandlerId%20value/trigger",
    "expectedQs": {},
    "expectedBody": {
      "mode": "live",
      "idempotencyKey": "idempotencyKey-value"
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  },
  {
    "operationId": "getNotificationHandler",
    "resource": "notificationHandler",
    "method": "GET",
    "parameters": [
      "projectId",
      "notificationHandlerId"
    ],
    "bodyFieldNames": [],
    "hasCustomerAttributeMapper": false,
    "inputData": {
      "projectId": "projectId value",
      "notificationHandlerId": "notificationHandlerId value"
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/nudge/projects/projectId%20value/notification-handlers/notificationHandlerId%20value",
    "expectedQs": {},
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  },
  {
    "operationId": "getAllNotificationHandlersInProject",
    "resource": "notificationHandler",
    "method": "GET",
    "parameters": [
      "projectId",
      "search",
      "page",
      "size"
    ],
    "bodyFieldNames": [],
    "hasCustomerAttributeMapper": false,
    "inputData": {
      "projectId": "projectId value",
      "search": "search-value",
      "page": "page-value",
      "size": "size-value"
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/nudge/projects/projectId%20value/notification-handlers/",
    "expectedQs": {
      "search": "search-value",
      "page": "page-value",
      "size": "size-value"
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  },
  {
    "operationId": "associateCustomerToTargetAudienceList",
    "resource": "targetAudienceList",
    "method": "POST",
    "parameters": [
      "projectId",
      "targetAudienceListId"
    ],
    "bodyFieldNames": [
      "customerIds"
    ],
    "hasCustomerAttributeMapper": false,
    "inputData": {
      "projectId": "projectId value",
      "targetAudienceListId": "targetAudienceListId value",
      "customerIds": {
        "customerIds": [
          {
            "value": "customerIds-1"
          },
          {
            "value": "customerIds-2"
          }
        ]
      }
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/nudge/projects/projectId%20value/target-audience-lists/targetAudienceListId%20value/customers",
    "expectedQs": {},
    "expectedBody": {
      "customerIds": [
        "customerIds-1",
        "customerIds-2"
      ]
    },
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  },
  {
    "operationId": "deleteCustomerFromTargetAudienceList",
    "resource": "targetAudienceList",
    "method": "PATCH",
    "parameters": [
      "targetAudienceListId",
      "customerId",
      "projectId"
    ],
    "bodyFieldNames": [],
    "hasCustomerAttributeMapper": false,
    "inputData": {
      "targetAudienceListId": "targetAudienceListId value",
      "customerId": "customerId value",
      "projectId": "projectId value"
    },
    "expectedUrl": "https://api-200422742317.asia-south1.run.app/api/v1/dokaai/nudge/projects/projectId%20value/target-audience-lists/targetAudienceListId%20value/customer/customerId%20value",
    "expectedQs": {},
    "expectedAuthHeaders": {
      "x-client-key": "x-client-key-value",
      "x-client-secret": "x-client-secret-value"
    }
  }
];

const getNodeParameterContext = (inputData) => ({
	getNodeParameter: (name, _itemIndex, defaultValue) =>
		Object.prototype.hasOwnProperty.call(inputData, name)
			? inputData[name]
			: defaultValue,
});

test('Dokaai node exposes selected OpenAPI operations by n8n resource', () => {
	const node = new Dokaai();
	const resourceProperty = node.description.properties.find((property) => property.name === 'resource');

	assert.ok(resourceProperty);
	assert.deepEqual(
		resourceProperty.options.map((option) => option.value),
		Object.keys(operationsByResource),
	);

	for (const [resource, operationIds] of Object.entries(operationsByResource)) {
		const operationProperty = node.description.properties.find(
			(property) =>
				property.name === 'operation' &&
				property.displayOptions?.show?.resource?.includes(resource),
		);

		assert.ok(operationProperty, `Missing operation selector for resource ${resource}`);
		assert.deepEqual(
			operationProperty.options.map((option) => option.value),
			operationIds,
		);
	}
});

test('Dokaai node generates expected fields from OpenAPI params and request bodies', () => {
	const node = new Dokaai();

	for (const fixture of operationFixtures) {
		const fields = node.description.properties.filter((property) =>
			property.displayOptions?.show?.operation?.includes(fixture.operationId),
		);
		const fieldNames = fields.map((field) => field.name);

		for (const parameter of fixture.parameters) {
			assert.ok(
				fieldNames.includes(parameter),
				`${fixture.operationId} should include parameter field ${parameter}`,
			);
		}

		for (const bodyFieldName of fixture.bodyFieldNames) {
			assert.ok(
				fieldNames.includes(bodyFieldName),
				`${fixture.operationId} should include body field ${bodyFieldName}`,
			);
		}

		if (fixture.hasCustomerAttributeMapper) {
			const mapperField = fields.find((field) => field.name === 'customerAttributes');
			assert.equal(mapperField?.type, 'resourceMapper');
			assert.deepEqual(mapperField.typeOptions?.loadOptionsDependsOn, [
				'projectId',
				'customerPoolId',
			]);
		}
	}
});

test('Dokaai request builder matches OpenAPI method, URL, auth, query, and body shape', () => {
	for (const fixture of operationFixtures) {
		const definition = findOperationById(dokaaiOpenApiDocument, fixture.operationId);
		const values = readOperationValues(
			getNodeParameterContext(fixture.inputData),
			definition.operation,
			undefined,
			0,
		);
		const request = buildRequestOptions(dokaaiOpenApiDocument, definition, values, {
			clientKey: 'x-client-key-value',
			clientSecret: 'x-client-secret-value',
		});

		assert.equal(request.method, fixture.method);
		assert.equal(request.url, fixture.expectedUrl);
		assert.deepEqual(request.qs, fixture.expectedQs);
		assert.deepEqual(
			{
				'x-client-key': request.headers['x-client-key'],
				'x-client-secret': request.headers['x-client-secret'],
			},
			fixture.expectedAuthHeaders,
		);

		if (fixture.expectedBody === undefined) {
			assert.equal(request.body, undefined);
		} else {
			assert.deepEqual(request.body, fixture.expectedBody);
		}
	}
});
